# Generated by Django 2.0.7 on 2019-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FORM_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chart_No', models.CharField(max_length=50)),
                ('Pathological_Section', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
